In [1]:
import pickle
import pandas as pd
import numpy as np

In [15]:
# Function to load data
def load_pickle(file_path):
    with open(file_path, 'rb') as handle:
        content = pickle.load(handle)
    return content

# Function to print solutions
def print_solution(file_path):
    solution = load_pickle(output_path + file_name)
    
    # Objective
    print("Unsatisfied Demand (to minimize)")
    print("SA: {}".format(solution['sa']['unsatisfied_customers']))
    print("ACO: {}".format(solution['aco']['unsatisfied_customers']))
    
    # Time
    print("Time")
    print("SA: {}".format(solution['sa']['time']))
    print("ACO: {}".format(solution['aco']['time']))

    print("\nSA Route")
    for i, df in solution['sa']['route_df'].items():
        print("Truck {}:".format(i))
        display(df)
        
    print("ACO Route")
    for i, df in solution['aco']['route_df'].items():
        print("Truck {}:".format(i))
        display(df)

    print("\nSA Station Inventory")
    display(solution['sa']['station_inv_df'])
    print("ACO Station Inventory")
    display(solution['aco']['station_inv_df'])

**Notes:**
* The cases come from historical data. The solution files are named using the template `solution_<num>stops_<case_date>_<case_time_window>_<versin>`.
* 'redist' column: the number of bikes at station after redistribution
* 'expected' column: the number of bikes expected at station based on forecasted inflows and outflows
* 'actual' column: the number of bikes current at the station; extracted from sensor data
* In SA, action < 0 means pick-ups; In ACO, action > 0 means pickups. Ouch...

In [13]:
solution = load_pickle(output_path + file_name)

In [14]:
solution

{'sa': {'iterations': 8000,
  'unsatisfied_customers': 4.0,
  'time': 76.585,
  'route_df': {0:     stop  action      time  truck_inv  actual  expected  redist
   0      7    -2.0  0.000000        2.0     3.0         1     1.0
   1     41   -11.0  4.671667       13.0    12.0         1     1.0
   2    145    -2.0  6.053333       15.0     6.0         1     1.0
   3    142    15.0  1.778333        0.0     1.0        30    30.0
   4    134   -11.0  7.481667       11.0    12.0         1     1.0
   5     77    -4.0  1.968333       15.0    31.0         1     1.0
   6     98    11.0  1.520000        4.0     0.0        11    11.0
   7     96    -6.0  2.553333       10.0     7.0         1     1.0
   8     80    -5.0  2.265000       15.0     7.0         1     2.0
   9    110     7.0  6.150000        8.0     0.0        22    22.0
   10   196     4.0  1.630000        4.0     1.0        20    20.0
   11   145    -3.0  2.033333        7.0     6.0         1     1.0
   12   176    -8.0  2.146667       15.0    37.0         1     4.0
   13     7     0.0  6.375000       15.0     3.0         1     NaN,
   1:     stop  action      time  truck_inv  actual  expected  redist
   0      7     0.0  0.000000       -0.0     3.0         1     1.0
   1    182   -15.0  6.405000       15.0    22.0         7     7.0
   2    110    15.0  2.373333        0.0     0.0        22    22.0
   3    176   -15.0  1.923333       15.0    37.0         1     4.0
   4    197    15.0  4.730000        0.0     0.0        18    18.0
   5     56    -4.0  3.886667        4.0     5.0         1     1.0
   6    197     3.0  4.190000        1.0     0.0        18    18.0
   7     73    -2.0  3.110000        3.0     3.0         1     1.0
   8    301   -12.0  6.730000       15.0    17.0         1     1.0
   9    142    14.0  4.475000        1.0     1.0        30    30.0
   10   172    -5.0  2.715000        6.0     7.0         2     2.0
   11   180    -9.0  1.258333       15.0    11.0         2     2.0
   12    38    15.0  4.480000        0.0     0.0        25    25.0
   13    77   -15.0  2.116667       15.0    31.0         1     1.0
   14   196    15.0  4.300000        0.0     1.0        20    20.0
   15   301    -4.0  4.383333        4.0    17.0         1     1.0
   16    77   -11.0  6.178333       15.0    31.0         1     1.0
   17    38    10.0  3.295000        5.0     0.0        25    25.0
   18   176   -10.0  3.660000       15.0    37.0         1     4.0
   19     7     0.0  6.375000       15.0     3.0         1     1.0},
  'station_inv_df':     stop  actual  expected  redist  diff
  0      7     3.0         1     1.0   0.0
  1     38     0.0        25    25.0   0.0
  2     41    12.0         1     1.0   0.0
  3     56     5.0         1     1.0   0.0
  4     73     3.0         1     1.0   0.0
  5     77    31.0         1     1.0   0.0
  6     80     7.0         1     2.0   1.0
  7     96     7.0         1     1.0   0.0
  8     98     0.0        11    11.0   0.0
  9    110     0.0        22    22.0   0.0
  10   134    12.0         1     1.0   0.0
  11   142     1.0        30    30.0   0.0
  12   145     6.0         1     1.0   0.0
  13   172     7.0         2     2.0   0.0
  14   176    37.0         1     4.0   3.0
  15   180    11.0         2     2.0   0.0
  16   182    22.0         7     7.0   0.0
  17   196     1.0        20    20.0   0.0
  18   197     0.0        18    18.0   0.0
  19   301    17.0         1     1.0   0.0},
 'aco': {'time': 50.52166666666667,
  'satisfied_customers': 278.0,
  'unsatisfied_customers': 4.0,
  'route_df': {0:     stop      time  truck_inv  action  actual  expected  redist
   0      7  0.000000        2.0     2.0     3.0         1     1.0
   1     41  4.671667       13.0    11.0    12.0         1     1.0
   2    197  2.493333        0.0   -13.0     0.0        18    13.0
   3     80  4.443333        6.0     6.0     7.0         1     1.0
   4     96  2.806667       12.0     6.0     7.0         1     1.0
   5    196  4.325000        0.0   -12.0     1.0        20    13.0
   6    176  3.551667       15.0    15.0    37.0         1    22.0
   7    196  3.551667        8.0    -7.0     1.0        20     8.0
   8    145  2.033333       13.0     5.0     6.0         1     1.0
   9    176  2.146667       15.0     2.0    37.0         1    35.0
   10   110  1.920000        0.0   -15.0     0.0        22    15.0
   11   301  2.756667       15.0    15.0    17.0         1     2.0
   12    38  4.078333        0.0   -15.0     0.0        25    15.0
   13    56  2.713333        4.0     4.0     5.0         1     1.0
   14   134  2.773333       15.0    11.0    12.0         1     1.0
   15     7  6.256667       15.0     0.0     3.0         1     NaN,
   1:     stop      time  truck_inv  action  actual  expected  redist
   0      7  0.000000        0.0     0.0     3.0         1     3.0
   1     77  4.358333       15.0    15.0    31.0         1    16.0
   2     98  1.520000        4.0   -11.0     0.0        11    11.0
   3     77  1.420000       15.0    11.0    31.0         1    20.0
   4    197  2.780000       10.0    -5.0     0.0        18     5.0
   5     77  2.285000       14.0     4.0    31.0         1    27.0
   6    142  5.495000        0.0   -14.0     1.0        30    15.0
   7    172  2.715000        5.0     5.0     7.0         2     2.0
   8    180  1.258333       14.0     9.0    11.0         2     2.0
   9    176  1.423333       15.0     1.0    37.0         1    36.0
   10   142  3.548333        0.0   -15.0     1.0        30    16.0
   11   176  3.300000       15.0    15.0    37.0         1    22.0
   12   110  1.920000        8.0    -7.0     0.0        22     7.0
   13   301  2.756667        9.0     1.0    17.0         1    16.0
   14   176  0.926667       12.0     3.0    37.0         1    34.0
   15    38  3.151667        2.0   -10.0     0.0        25    10.0
   16   182  4.110000       15.0    13.0    22.0         7     9.0
   17     7  6.826667       15.0     0.0     3.0         1     NaN},
  'station_inv_df':     stop  actual  expected  redist  diff
  0      7     3.0         1     1.0   0.0
  1     38     0.0        25    25.0   0.0
  2     41    12.0         1     1.0   0.0
  3     56     5.0         1     1.0   0.0
  4     73     3.0         1     3.0   2.0
  5     77    31.0         1     1.0   0.0
  6     80     7.0         1     1.0   0.0
  7     96     7.0         1     1.0   0.0
  8     98     0.0        11    11.0   0.0
  9    110     0.0        22    22.0   0.0
  10   134    12.0         1     1.0   0.0
  11   142     1.0        30    30.0   0.0
  12   145     6.0         1     1.0   0.0
  13   172     7.0         2     2.0   0.0
  14   176    37.0         1     1.0   0.0
  15   180    11.0         2     2.0   0.0
  16   182    22.0         7     9.0   2.0
  17   196     1.0        20    20.0   0.0
  18   197     0.0        18    18.0   0.0
  19   301    17.0         1     1.0   0.0}}

In [16]:
output_path = '/Users/xuanlin/Desktop/Capstone/Optimization/output/'
file_name = 'demo_2truck_multivisit_20stops_2018-08-15_4_1.pickle'
print_solution(output_path + file_name)

Unsatisfied Demand (to minimize)
SA: 4.0
ACO: 4.0
Time
SA: 76.585
ACO: 50.52166666666667

SA Route
Truck 0:

    stop  action      time  truck_inv  actual  expected  redist
0      7    -2.0  0.000000        2.0     3.0         1     1.0
1     41   -11.0  4.671667       13.0    12.0         1     1.0
2    145    -2.0  6.053333       15.0     6.0         1     1.0
3    142    15.0  1.778333        0.0     1.0        30    30.0
4    134   -11.0  7.481667       11.0    12.0         1     1.0
5     77    -4.0  1.968333       15.0    31.0         1     1.0
6     98    11.0  1.520000        4.0     0.0        11    11.0
7     96    -6.0  2.553333       10.0     7.0         1     1.0
8     80    -5.0  2.265000       15.0     7.0         1     2.0
9    110     7.0  6.150000        8.0     0.0        22    22.0
10   196     4.0  1.630000        4.0     1.0        20    20.0
11   145    -3.0  2.033333        7.0     6.0         1     1.0
12   176    -8.0  2.146667       15.0    37.0         1     4.0
13     7     0.0  6.375000       15.0     3.0         1     NaN

Truck 1:

    stop  action      time  truck_inv  actual  expected  redist
0      7     0.0  0.000000       -0.0     3.0         1     1.0
1    182   -15.0  6.405000       15.0    22.0         7     7.0
2    110    15.0  2.373333        0.0     0.0        22    22.0
3    176   -15.0  1.923333       15.0    37.0         1     4.0
4    197    15.0  4.730000        0.0     0.0        18    18.0
5     56    -4.0  3.886667        4.0     5.0         1     1.0
6    197     3.0  4.190000        1.0     0.0        18    18.0
7     73    -2.0  3.110000        3.0     3.0         1     1.0
8    301   -12.0  6.730000       15.0    17.0         1     1.0
9    142    14.0  4.475000        1.0     1.0        30    30.0
10   172    -5.0  2.715000        6.0     7.0         2     2.0
11   180    -9.0  1.258333       15.0    11.0         2     2.0
12    38    15.0  4.480000        0.0     0.0        25    25.0
13    77   -15.0  2.116667       15.0    31.0         1     1.0
14   196    15.0  4.300000        0.0     1.0        20    20.0
15   301    -4.0  4.383333        4.0    17.0         1     1.0
16    77   -11.0  6.178333       15.0    31.0         1     1.0
17    38    10.0  3.295000        5.0     0.0        25    25.0
18   176   -10.0  3.660000       15.0    37.0         1     4.0
19     7     0.0  6.375000       15.0     3.0         1     1.0

ACO Route
Truck 0:

    stop      time  truck_inv  action  actual  expected  redist
0      7  0.000000        2.0     2.0     3.0         1     1.0
1     41  4.671667       13.0    11.0    12.0         1     1.0
2    197  2.493333        0.0   -13.0     0.0        18    13.0
3     80  4.443333        6.0     6.0     7.0         1     1.0
4     96  2.806667       12.0     6.0     7.0         1     1.0
5    196  4.325000        0.0   -12.0     1.0        20    13.0
6    176  3.551667       15.0    15.0    37.0         1    22.0
7    196  3.551667        8.0    -7.0     1.0        20     8.0
8    145  2.033333       13.0     5.0     6.0         1     1.0
9    176  2.146667       15.0     2.0    37.0         1    35.0
10   110  1.920000        0.0   -15.0     0.0        22    15.0
11   301  2.756667       15.0    15.0    17.0         1     2.0
12    38  4.078333        0.0   -15.0     0.0        25    15.0
13    56  2.713333        4.0     4.0     5.0         1     1.0
14   134  2.773333       15.0    11.0    12.0         1     1.0
15     7  6.256667       15.0     0.0     3.0         1     NaN

Truck 1:

    stop      time  truck_inv  action  actual  expected  redist
0      7  0.000000        0.0     0.0     3.0         1     3.0
1     77  4.358333       15.0    15.0    31.0         1    16.0
2     98  1.520000        4.0   -11.0     0.0        11    11.0
3     77  1.420000       15.0    11.0    31.0         1    20.0
4    197  2.780000       10.0    -5.0     0.0        18     5.0
5     77  2.285000       14.0     4.0    31.0         1    27.0
6    142  5.495000        0.0   -14.0     1.0        30    15.0
7    172  2.715000        5.0     5.0     7.0         2     2.0
8    180  1.258333       14.0     9.0    11.0         2     2.0
9    176  1.423333       15.0     1.0    37.0         1    36.0
10   142  3.548333        0.0   -15.0     1.0        30    16.0
11   176  3.300000       15.0    15.0    37.0         1    22.0
12   110  1.920000        8.0    -7.0     0.0        22     7.0
13   301  2.756667        9.0     1.0    17.0         1    16.0
14   176  0.926667       12.0     3.0    37.0         1    34.0
15    38  3.151667        2.0   -10.0     0.0        25    10.0
16   182  4.110000       15.0    13.0    22.0         7     9.0
17     7  6.826667       15.0     0.0     3.0         1     NaN

SA Station Inventory

    stop  actual  expected  redist  diff
0      7     3.0         1     1.0   0.0
1     38     0.0        25    25.0   0.0
2     41    12.0         1     1.0   0.0
3     56     5.0         1     1.0   0.0
4     73     3.0         1     1.0   0.0
5     77    31.0         1     1.0   0.0
6     80     7.0         1     2.0   1.0
7     96     7.0         1     1.0   0.0
8     98     0.0        11    11.0   0.0
9    110     0.0        22    22.0   0.0
10   134    12.0         1     1.0   0.0
11   142     1.0        30    30.0   0.0
12   145     6.0         1     1.0   0.0
13   172     7.0         2     2.0   0.0
14   176    37.0         1     4.0   3.0
15   180    11.0         2     2.0   0.0
16   182    22.0         7     7.0   0.0
17   196     1.0        20    20.0   0.0
18   197     0.0        18    18.0   0.0
19   301    17.0         1     1.0   0.0

ACO Station Inventory

    stop  actual  expected  redist  diff
0      7     3.0         1     1.0   0.0
1     38     0.0        25    25.0   0.0
2     41    12.0         1     1.0   0.0
3     56     5.0         1     1.0   0.0
4     73     3.0         1     3.0   2.0
5     77    31.0         1     1.0   0.0
6     80     7.0         1     1.0   0.0
7     96     7.0         1     1.0   0.0
8     98     0.0        11    11.0   0.0
9    110     0.0        22    22.0   0.0
10   134    12.0         1     1.0   0.0
11   142     1.0        30    30.0   0.0
12   145     6.0         1     1.0   0.0
13   172     7.0         2     2.0   0.0
14   176    37.0         1     1.0   0.0
15   180    11.0         2     2.0   0.0
16   182    22.0         7     9.0   2.0
17   196     1.0        20    20.0   0.0
18   197     0.0        18    18.0   0.0
19   301    17.0         1     1.0   0.0